### PR TITLE
Fix parsing of def using flags

### LINKED ISSUE #49: Parsing of `def` with flags fails
スクリーンショット 2023-12-27 221408

### PR DESCRIPTION
**Pull request by kit494way**
Fix #49

### CODE REVIEW

**Comment by fdncred** [comment]
I see these tested
```nushell
def --env foo [] {}
def --env --wrapped bar [...args] {}
```
but does it cover these?
```
def --wrapped --env foo [] {}
def --wrapped bar [...args] {}
```

**Comment by stevenxxiu** [comment]
I also wonder if `def-env` should be changed to `def --env`?

**Comment by fdncred** [comment]
@stevenxxiu I don't follow. Where is `def-env` used in this PR?

**Comment by stevenxxiu** [comment]
@fdncred There are some in the tests and some in `grammar.js`, but this is now removed.

**Comment by fdncred** [comment]
if we still have `def-env` anywhere, it needs to be removed, but not necessarily in this PR.

**Comment by stevenxxiu** [comment]
That could make sense, but would it be better to directly change the `def-env` tests to `def --env`, and remove `def-env` at the same time?

**Comment by kit494way** [comment]
@fdncred @stevenxxiu Thanks for your reviews. I will remove `def-env` and fix the tests in this PR.

**Comment by kit494way** [comment]
I removed `def-env` and fixed the tests.

**Comment by fdncred** [comment]
Thanks. looks good!

**Pull request merged**
