### PR TITLE
FEATURE: add highlights query

### PR DESCRIPTION
**Pull request by amtoine**
Related to #5.

@1Kinoti i really wanted to have the hightlights for *neovim* so i took the [ones from your fork](https://github.com/nushell/tree-sitter-nu/compare/main...1Kinoti:tree-sitter-nu:main) and made these PR :innocent: 

# changes
> **Note**
> extra details in the commit bodies
 
- e579d5b762a38e7796318466e83e39412849fb11: get the raw file from @1Kinoti's fork
- fa9607cdfdc1a25588e0b88075793ab628d51a75: format the file a bit.
i do not know a lot about the syntax but i went with 4 spaces and, i hope, a consistent format across the file :relieved:

### CODE REVIEW

**Comment by 1Kinoti** [comment]
did you test it out to make sure the syntax highlighting works?

**Comment by amtoine** [comment]
> did you test it out to make sure the syntax highlighting works?
>
yes i did and i think it looks great, at least a looooot better than just a wall of white text :open_mouth: 

nu-treesitte

**Comment by 1Kinoti** [comment]
that looks gooood!

**Comment by amtoine** [comment]
> that looks gooood!
>
yeeeeah :star_struck: 

and the goal of this really is to have a base to build upong :yum:

**Comment by fdncred** [comment]
Nice. Thanks for the screenshot. Let's keep on chugging.

**Pull request merged**
