### PR TITLE
Fix parsing of export const

### LINKED ISSUE #34: Exports fail to highlight after first occurence
Zed
SCR-20231129-pcpz

Helix
SCR-20231129-pcts

```nu
export const GAMMA = 0.5772156649015329
export const E = 2.718281828459045
export const PI = 3.141592653589793
export const TAU = 6.283185307179586
export const PHI = 1.618033988749895
```

https://github.com/nushell/nushell/blob/main/crates/nu-std/std/math.nu

### PR DESCRIPTION
**Pull request by kit494way**
Fix #34

### CODE REVIEW

**Comment by fdncred** [comment]
Thanks for this! I'm wondering if it's possible to have another test that specifically tests the #34 scenario where multiple in a row get recognized properly?

**Comment by kit494way** [comment]
Add a test case for #34

**Comment by fdncred** [comment]
Thanks!

**Comment by JosephTLyons** [comment]
Thank you so much @kit494way, we're going to bump our internal version in Zed to include this commit :)

**Pull request merged**
