### PR TITLE
add extern optional block

### PR DESCRIPTION
**Pull request by 1Kinoti**
response to [#8956](https://github.com/nushell/nushell/pull/8956)

### CODE REVIEW

**Comment by fdncred** [comment]
should parser.c be in .gitignore or is it important to always have the latest in the repo?

**Comment by 1Kinoti** [comment]
mmmh, i wonder. but removing it would need users, i.e editors to build it for themselves. `nvim-treesitter` can do that, but i wonder if others (helix and lapce) can

**Comment by fdncred** [comment]
if people need it complete when downloaded, then it's fine to leave it, but if they're always going to rebuild, then it's probably not necessary. i'm leaning toward leaving it for now.

**Comment by 1Kinoti** [comment]
fwiw, tree-sitter-rust keep it in [tree](https://github.com/tree-sitter/tree-sitter-rust/blob/master/src/parser.c)

**Comment by fdncred** [comment]
ya, we should follow their lead. Thanks!

**Pull request merged**
