### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by kit494way**
Fix some typos

### CODE REVIEW

**Comment by fdncred** [comment]
not sure what's going on with the ci failures.

**Comment by kit494way** [comment]
The same error occurs on the main branch.

Unfortunately old image was used in ci.

> Runner Image
  Image: macos-12
  Version: 20231029.1
  Included Software: https://github.com/actions/runner-images/blob/macOS-12/20231029.1/images/macos/macos-12-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20231029.1

On this image, node-gyp@9.4.0 and Python 3.12 is used.
Python 3.12 removed `distutils` and node-gyp@9.4.0 does not support Python 3.12.
Updating npm will fix the failure, because node-gyp is installed as dependency of npm.

**Comment by amtoine** [comment]
let's try the CI :crossed_fingers:

**Comment by fdncred** [comment]
Wondering if this will fix the problem?
https://github.com/prettier/prettier/issues/7853#issuecomment-603843422

**Comment by fdncred** [comment]
yay!

**Pull request merged**
