### PR TITLE
Feat: internal commands with spaces

### PR DESCRIPTION
**Pull request by blindFS**
For test purpose #156

### CODE REVIEW

**Comment by fdncred** [comment]
Seems to work pretty good to me
image

**Comment by blindFS** [comment]
@fdncred yes, it works, but the dirty hack somehow worries me a little bit :-)

**Comment by fdncred** [comment]
I just noticed that the INTERNAL only has commands with spaces in them vs the entire list of commands. Is that because the single word commands are already captured elsewhere?

**Comment by blindFS** [comment]
> I just noticed that the `INTERNAL` function only has commands with spaces in them vs the entire list of commands. Is that because the single word commands are already captured elsewhere?

Yes, as the `cmd_identifier`.

**Comment by fdncred** [comment]
Also keep in mind that in order to get commands and plugins with spaces in them, you have to have the plugins built, installed, and registered for this command below to work. Also, that command would get multiword aliases and custom commands too.
```nushell
scope commands | get name | where {' ' in $in} o> list
```
This is the command below is probably more appropriate. It could be easily tweaked to include only the commands/plugin commands with spaces in them. We could also include `command_type == external` and that adds whatever custom completions you have loaded. 🤔 
```nushell
# generated with Nu 0.100.1
help commands | 
   where command_type == built-in or command_type == plugin or command_type == keyword |
   get name | 
   where {' ' in $in}
```

**Comment by blindFS** [comment]
Current implementation can't tell internals/externals from each other, if we want them highlighted differently, more complicated `cmd_identifier` is necessary.

**Comment by fdncred** [comment]
I'm not saying that they should be highlighted differently. I'm just saying that the help commands or scope commands only needs to list the appropriate things. e.g. custom commands should not be included in our list.

**Comment by blindFS** [comment]
> I'm not saying that they should be highlighted differently. I'm just saying that the help commands or scope commands only needs to list the appropriate things. e.g. custom commands should not be included in our list.

Sure, this pr is just a demo, we should redesign pipeline to generate the list.

**Comment by fdncred** [comment]
I have the `rustup`, `cargo`, `git` and `gh` custom completions loaded (along with keywords, builtins and plugins) and I have a list of 531 commands with spaces in them. I can provide that list or just update this PR before landing it.

**Comment by blindFS** [comment]
Does your script above generate all 531 of those commands? If so, we can add that script along with the generated list file to the repo. But I guess only you can maintain that list right? We probably only get a small part of it with the same script?

**Comment by blindFS** [comment]
We probably should test the impact on performance, 531 seems to be a significant number.

**Comment by blindFS** [comment]
@fdncred Do we need `cargo xxx` in the list?

**Comment by fdncred** [comment]
We can remove any of them that we want. However, I'm not sure 19 commands will make any difference. These are just the custom completions I usually run with `rustup`, `cargo`, `git` and `gh`.

**Comment by blindFS** [comment]
@fdncred we can keep it and update the test case,

the performance loss is about 7~8%, `4757/5136 bytes/ms`

**Pull request merged**
